# 第 2 章 丰富的序列


In [1]:
import sys
print(sys.version)
print(sys.executable)

3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
D:\ProgramData\anaconda3\python.exe


In [4]:
a ='a'
ord(a) # ord() 函数是 chr() 函数（对于8位的ASCII字符串）或 unichr() 函数（对于Unicode对象）的配对函数

97

In [6]:
from collections import abc 
issubclass(tuple,abc.Sequence)

True

In [7]:
issubclass(list, abc.MutableSequence)

True

## 列表推导式和生成器表达式
> 很多 Python 程序员把列表推导式简称为 listcomps，把生成 器表达式简称为 genexp。

### 列表推导式

In [12]:
# 方法一：
symbols = '$¢£¥€¤'   # 定义 Unicode 码点列表
codes = []
for symbol in symbols:  # 迭代
    codes.append(ord(symbol))
codes

[36, 162, 163, 165, 8364, 164]

In [13]:
# 方法二：
symbols =  '$¢£¥€¤'   # 定义 Unicode 码点列表
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

句法提示：Python 会忽略 []、{} 和 () 内部的换行。因此，列表、列表推 导式、元组、字典等结构完全可以分成几行来写，无须使用续行转 义符 \。

海象运算符：即一个变量名后跟一个表达式或者一个值，这个和赋值运算符 = 类似，可以看作是一种新的赋值运算符。

参考：https://zhuanlan.zhihu.com/p/351140647

In [17]:
x = 'ABC'
codes = [ord(x) for x in x]
x

'ABC'

In [18]:
codes

[65, 66, 67]

In [19]:
codes = [last := ord(c) for c in x]

In [20]:
last

67

In [24]:
# 加上条件
# 方法1
symbols =  '$¢£¥€¤'   # 定义 Unicode 码点列表
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii


[162, 163, 165, 8364, 164]

In [25]:
# 方法2
beyond_ascii = list(filter(lambda c: c>127,map(ord,symbols)))
beyond_ascii

[162, 163, 165, 8364, 164]

In [27]:
list(map(ord,symbols))  # map(function, iterable, ...)会根据提供的函数对指定序列做映射 

[36, 162, 163, 165, 8364, 164]

笛卡尔积：

In [28]:
colors = ['black','white']
sizes = ['S','M','L']
tshirts = [(color,size) for color in colors
                        for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [30]:
for color in colors:
    for size in sizes:
        print((color,size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


### 生成器表达式

In [31]:
symbols =  '$¢£¥€¤'   # 定义 Unicode 码点列表
tuple(ord(s) for s in symbols if ord(s) > 127)


(162, 163, 165, 8364, 164)

In [34]:
import array
symbols =  '$¢£¥€¤'   # 定义 Unicode 码点列表
array.array('i',(ord(s) for s in symbols if ord(s) > 127))

array('i', [162, 163, 165, 8364, 164])

In [79]:
# 使用生成器表达式计算笛卡尔积

colors = ['black','white']
sizes = ['s','m','l']

for tshirt in (f'{c},{s}' for c in colors for s in sizes):
    print(tshirt)


black,s
black,m
black,l
white,s
white,m
white,l


In [40]:
for tshirt in ((color,size) for c in colors for s in sizes):
    print(tshirt)

('white', 'L')
('white', 'L')
('white', 'L')
('white', 'L')
('white', 'L')
('white', 'L')


### 元组

In [44]:
lax_coordinates = (33.9425,-118.408056)
city,year,pop,chg,area = ('Tokyo',2003,32_450,_,_)

In [48]:
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'),('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [80]:
latitude ,longitude = lax_coordinates  # 拆包

In [81]:
latitude

33.9425

In [82]:
longitude

-118.408056

In [94]:
for c ,_ in traveler_ids:
    print(c)

USA
BRA
ESP


In [83]:
a = (10, 'alpha', [1, 2]) 
b = (10, 'alpha', [1, 2])
a

(10, 'alpha', [1, 2])

In [84]:
b

(10, 'alpha', [1, 2])

In [54]:
a==b

True

In [85]:
b[-1].append(3)

In [86]:
b

(10, 'alpha', [1, 2, 3])

In [87]:
d =(10, 'alpha', [1, 2,3])

In [88]:
b==d

True

In [89]:
b,a = a,b     # 并行赋值

In [90]:
b

(10, 'alpha', [1, 2])

In [91]:
a

(10, 'alpha', [1, 2, 3])

In [100]:
## 调用函数时在参数前面加一个*, 利用的也是拆包

divmod(20,8)  # Python divmod() 函数接收两个数字类型（非复数）参数，返回一个包含商和余数的元组(a // b, a % b)。


(2, 4)

In [102]:
t = (20,8)

divmod(*t)

(2, 4)

In [104]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [105]:
quotient

2

In [76]:
def fixed(o):
    try:
        hash(o)
    except TypeError:
        return False
    return True

In [77]:
tf = (10,'alpha',(1,2))
fixed(tf)

True

In [78]:
tm = (10,'alpha',[1,2])
fixed(tm)

False

In [106]:
import os 
_,filename = os.path.split('/home/luciano/.ssh/id_rsa.pub')
filename

'id_rsa.pub'

In [107]:
# 并行赋值时，*前缀只能应用到一个变量上，可以是任何位置上的变量。
a,b,*rest = range(5)
a,b,rest

(0, 1, [2, 3, 4])

In [108]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [109]:
# 函数中多次使用
def fun(a,b,c,d,*rest):
    return a,b,c,d,rest

fun(*[1,2],3,*range(4,7))

(1, 2, 3, 4, (5, 6))

In [110]:
# 定义元组和列表,集合字面量

*range(4),4

(0, 1, 2, 3, 4)

In [113]:
[*range(4),4]  # 列表

[0, 1, 2, 3, 4]

In [112]:
{*range(4), 4, *(5, 6, 7)} # 集合字面量

{0, 1, 2, 3, 4, 5, 6, 7}

### 嵌套拆包

In [120]:
# 嵌套拆包
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)), 
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)), 
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)), 
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)), 
]

def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":9}')  #f'{}'中的{}是一个占位符，表示要插入的位置
    for name,_,_, (lat,lon) in metro_areas:
        if lon<=0:
            print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')

if __name__ == '__main__':
    main()
    

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


### 序列模式匹配

模式匹配的用法很简单，和C语言的switch/case语句很像，但是其实更贴近Rust和Scala中的模式匹配。（这里往深了去似乎是函数式编程语言的内容）

match/case语句的语法很简

```
match 匹配对象（subject）:
    case 模式（pattern）:
        # 执行的过程
    case _: # 通配符，一般作为默认的模式
        # 执行的过程
```
单：

但是和拆包不同的是，match/case的析构不能匹配迭代器。

In [2]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}') #f'{}'中的{}是一个占位符，表示要插入的位置
    for record in metro_areas:
        match record:  # python>=3.10 
            case [name, _, _, (lat, lon)] if lon <= 0:
                 print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')

if __name__ == '__main__':
    main()


                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


In [4]:
# 详细见lis.py 
from lis import parse  
parse('(qcd 18 45)')

['qcd', 18, 45]

### 切片

In [5]:
l = [10,20,30,40,50,60]
l[:2]

[10, 20]

In [6]:
l[2:]

[30, 40, 50, 60]

In [7]:
l[3:]

[40, 50, 60]

In [8]:
s = 'bicycle'
s[::3]

'bye'

In [9]:
s[::-1]  # 倒叙

'elcycib'

In [10]:
s[::-2] 

'eccb'

In [11]:
s[::1]

'bicycle'

In [14]:
s[:]

'bicycle'

In [15]:
s[::2]

'bcce'

### 切片

In [23]:
# 从纯文本形式的发票中提取商品信息
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                     $17.50    3    $52.50
1489  6mm Tactile Switch x20                 $4.95    2     $9.90
1510  Panavise Jr. - PV-201                 $28.00    1    $28.00
1601  PiTFT Mini Kit 320x240                $34.95    1    $34.95
"""
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE],item[DESCRIPTION])

    $17.50   Pimoroni PiBrella                 
     $4.95   6mm Tactile Switch x20            
    $28.00   Panavise Jr. - PV-201             
    $34.95   PiTFT Mini Kit 320x240            
 


### 多维切片和省略号

In [25]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
l[2:5] = [20,30]

In [27]:
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [28]:
del l[5:7]

In [29]:
l

[0, 1, 20, 30, 5, 8, 9]

In [30]:
l[3::2] = [11, 22]

In [31]:
l

[0, 1, 20, 11, 5, 22, 9]

In [32]:
l[2:5] = 100

TypeError: can only assign an iterable

In [33]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

### 使用 + 和 * 处理序

In [34]:
l = [1,2,3]
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [35]:
5*'abcd'

'abcdabcdabcdabcdabcd'

In [39]:
f'{1:5}'

'    1'

In [40]:
{1:5}

{1: 5}

In [42]:
l = [1,2,3]
l+5  # 必须同一个序列

TypeError: can only concatenate list (not "int") to list

In [44]:
d = [5,6,7]

l+d  # 拼接

[1, 2, 3, 5, 6, 7]

### 构建嵌套列表


#### 情况一：

In [53]:
board = [['_'] * 3 for i in range(3)]
board

id(board)

2201771075328

In [49]:
board[1][2] = '*'
board

[['_', '_', '_'], ['_', '_', '*'], ['_', '_', '_']]

In [50]:
# 等价于
board = []
for i in range(3):
    row = ['_']*3
    board.append(row)

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

#### 情况二：

In [59]:
weird_board = [['_'] * 3] * 3

weird_board


[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [60]:
id(weird_board)

2201749342464

In [61]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [62]:
# 等价于

row = ['_'] * 3 
board = [] 
for i in range(3): 
    board.append(row)

In [63]:
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [64]:
board[1][2] = '*'
board

[['_', '_', '*'], ['_', '_', '*'], ['_', '_', '*']]

> 如果你不理解本节所讲的问题或解决方案，没关系。第 6 章 就是为了阐明引用和可变对象的机制和陷阱而编写的。

In [77]:
l = [1,2,3]
id(l)

2201855612416

In [79]:
l *=2

In [80]:
l

[1, 2, 3, 1, 2, 3]

In [81]:
id(l)

2201855612416

In [82]:
t = (1,2,3)
id(t)

2201855657152

In [84]:
t *=2

In [85]:
id(t)

2201772336768

In [87]:
# + 运算符

t = (1,2,[30,40])

t[2] +=[50,60]

TypeError: 'tuple' object does not support item assignment

In [89]:
t   # 上面报错，但是执行成功

(1, 2, [30, 40, 50, 60])

In [90]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [91]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [92]:
sorted(fruits, reverse=True) # 返回降序

['raspberry', 'grape', 'banana', 'apple']

In [93]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [95]:
sorted(fruits, key=len) # 根据长度排序

['grape', 'apple', 'banana', 'raspberry']

In [97]:
sorted(fruits, key=str.lower)  #不区分大小写

['apple', 'banana', 'grape', 'raspberry']

In [102]:
sorted(fruits, key=len,reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [103]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [104]:
fruits.sort()

In [105]:
fruits

['apple', 'banana', 'grape', 'raspberry']

## 当列表不适用时

### 数组

如果一个列表只包含数值，使用array.array会更高效。

更多操作：https://zhuanlan.zhihu.com/p/341673561

In [120]:
from array import array
test = array('u', 'ABCab')
print(test)
print(test[0])
print(test.typecode)
print(test.tolist())
print(test.tounicode())

array('u', 'ABCab')
A
u
['A', 'B', 'C', 'a', 'b']
ABCab


In [69]:
from array import array
from random import random

# 创建一个双精度浮点数数组
floats = array('d',(random() for i in  range(10**7)))
floats[0]               

0.2835877406973514

In [70]:
len(floats)

10000000

In [72]:
# 把数组存入一个二进制文件中
fp = open('./floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [73]:
import os
os.path.exists('./floats.bin')

True

In [74]:
# 从二进制文件中读取1000万个数
floats2 = array('d')
fp = open('./floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()

floats2[0]

0.2835877406973514

In [75]:
floats2 == floats

True

数组排序方法：  a = array.array(a.typecode, sorted(a))

### memoryview

内置的 memoryview 类是一种共享内存的序列类型，可在不复制字节 的情况下处理数组的切片。

In [106]:
from array import array

octets = array('B',range(6))


In [107]:
octets

array('B', [0, 1, 2, 3, 4, 5])

In [121]:
m1 = memoryview(octets) 

In [122]:
m1.tolist()

[0, 1, 2, 3, 4, 5]

In [123]:
m2 = m1.cast('B', [2, 3])

In [124]:
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [125]:
m3 = m1.cast('B', [3, 2])

In [126]:
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [127]:
m2[1,1] = 22

In [128]:
m3[1,1] = 33

In [129]:
octets

array('B', [0, 1, 2, 33, 22, 5])

In [155]:
from array import array
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [156]:
numbers1 = array('u', 'd')
numbers1[0]

'd'

In [157]:
memv_oct = memv.cast('B') # 元素转换成字节（类型代码为 'B'

In [158]:
memv_oct.tolist() 

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [159]:
numbers

array('h', [-2, -1, 0, 1, 2])

In [160]:
memv_oct[5] = 4 
numbers

array('h', [-2, -1, 1024, 1, 2])

### numpy

In [162]:
import numpy as np
a = np.arange(12)

In [163]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [164]:
type(a)

numpy.ndarray

In [165]:
a.shape

(12,)

In [168]:
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
a[2]

array([ 8,  9, 10, 11])

In [174]:
a[2:]

array([[ 8,  9, 10, 11]])

In [175]:
a[2,1]

9

In [176]:
a[:,1]

array([1, 5, 9])

In [190]:
import numpy 
a = np.arange(100)
a.shape=25,4
np.savetxt("./floats-10M-lines.txt", a,fmt ='%d')
a

In [192]:
import numpy 
floats = numpy.loadtxt('floats-10M-lines.txt')
floats[-3:]

array([[88., 89., 90., 91.],
       [92., 93., 94., 95.],
       [96., 97., 98., 99.]])

In [193]:
floats *= .5

In [194]:
floats[-3:]

array([[44. , 44.5, 45. , 45.5],
       [46. , 46.5, 47. , 47.5],
       [48. , 48.5, 49. , 49.5]])

In [195]:
from time import perf_counter as pc
t0 = pc(); floats /= 3; pc() - t0

7.609999738633633e-05

In [197]:
numpy.save('floats-10M', floats)

In [ ]:
floats2 = numpy.load('floats-10M.npy', 'r+')

In [198]:
floats2 *= 6
floats2[-3:]

array('d', [0.3827787366669586, 0.46794518186231304, 0.5657860185104016])

### 双端队列和其他队列


- deque类实现一种线程安全的双端队列，旨在快速在两端插入和删除项。
- 
queue提供几个同步（即线程安全）队列类，在队列填满后，阻塞插入新项，等待其他线程从队列中取出一项
- 
multiprocessiong单独实现了无界SimpleQueue和有界的Queu
- 。
asyncio提供了Queue、LifoQueue、PriorityQueue和JoinableQueue，为管理异步编程任务而做了  修改。

In [199]:
from collections import deque # 双端队列
dq = deque(range(10),maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [200]:
dq.rotate(3) # 把 n 项从一端移到另一端

In [201]:
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [202]:
dq.rotate(-4) #前面4项移到最后 

In [203]:
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

In [204]:
dq.rotate(-4)

In [205]:
dq

deque([5, 6, 7, 8, 9, 0, 1, 2, 3, 4], maxlen=10)

In [206]:
dq.appendleft(-1)  # 左追加

In [207]:
dq

deque([-1, 5, 6, 7, 8, 9, 0, 1, 2, 3], maxlen=10)

In [208]:
dq.appendleft(-1)
dq

deque([-1, -1, 5, 6, 7, 8, 9, 0, 1, 2], maxlen=10)

In [209]:
dq.extend([11, 22, 33])
dq

deque([6, 7, 8, 9, 0, 1, 2, 11, 22, 33], maxlen=10)

In [210]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 6, 7, 8, 9, 0, 1], maxlen=10)

In [211]:
dq.appendleft([1,2,3,4]) # 单个元素
dq

deque([[1, 2, 3, 4], 40, 30, 20, 10, 6, 7, 8, 9, 0], maxlen=10)

### 2.6 杂谈
元组的本质：ABC语言的compound类型是Python元组的前身。该类型还支持并行复制，也可用作字典的组合键。但是不是序列，不可迭代，不饿能通过索引获取字段，不能使用切片。  

扁平序列与容器序列：  

扁平序列：是不可嵌套的序列类型，只能包含简单的原子类型，例如整数、浮点数或字符。  
容器序列：可以嵌套，包含任何类型的对象，甚至是容器类型自身。  


大杂烩列表：  
 
如果列表中的项不可比较，就不能排序。  
如果元组中的每一项都是一个字段，那么每个字段就可以具有不同的类型。  


聪明的key：  

只需要定义一个单参数函数，通过它获取或计算用于排序对象的标准即可。  
高效：key指定的函数只在处理各项时调用一次，而双参数比较函数在每次需要通过排序算法比较两项时，都需要调用一次。  

甲骨文、谷歌和Timbot阴谋论：  

Oracle和list.sort使用的排序算法是Timsort，一种自适应算法，可根据数据的排序方法在插入排序法和归并排序法之间切换。  
Timsort于2002年首次在CPython使用。  
Timsort由Tim Peters发明，称为Timbot。  